### ISSUE TITLE
Pill error

### ISSUE THREAD

**Issue by phdstudent2022** [jonpry/Pill#2]
Hi Jonpry,

I am cad engineer learning.
Your Pill is looks to be very impressive.
I am trying to run example give the following error popped up.
Need your help ans support to clear the error.

Traceback (most recent call last):
  File "./entry.py", line 3, in <module>
    import interp
  File "/home/ATOOLS/jonpry/Pill/interp.py", line 44, in <module>
    from runtime import getsqg, setsqg
  File "/home/ATOOLS/jonpry/Pill/runtime.py", line 26, in <module>
    import klayout.lib
ModuleNotFoundError: No module named 'klayout.lib'

Please do suggest what to do?

**Comment by pryvision** [comment]
Hi,

   Have you install klayout or the klayout python packages? I think:

 pip install klayout

**Comment by phdstudent2022** [comment]
Thank you for your response. Let me check and revert you soon.

Regards,
Vijay

**Comment by phdstudent2022** [comment]
Hi jonpry,

Error remains the same as given below.

I followed same procedure given in github

Traceback (most recent call last):
  File "./entry.py", line 3, in <module>
    import interp
  File "/home/ATOOLS/jonpry/Pill/interp.py", line 44, in <module>
    from runtime import getsqg, setsqg
  File "/home/ATOOLS/jonpry/Pill/runtime.py", line 25, in <module>
    import klayout.db as db
ModuleNotFoundError: No module named 'klayout.db'

Please share me any document to install klayout python

Regards,
Vijay

**Comment by pryvision** [comment]
I built klayout from source. You might want to try that using these instructions https://www.klayout.de/build.html
